/**
 * Custom column types and shared column helpers for the Drizzle schema.
 *
 * Money rules enforced at the type level (CLAUDE.md "Cross-cutting technical rules"):
 * - Chain amounts are `NUMERIC(78,0)` in the database and `bigint` in TypeScript. 78 digits fit
 *   any uint256 value; nothing is ever read as a JavaScript `number`.
 * - Fiat amounts are integer minor units (`NUMERIC(38,0)` ↔ `bigint`): XOF francs, EUR cents.
 * - Rates and prices are `NUMERIC(38,18)` and stay exact decimal **strings** in TypeScript; they
 *   are converted with `@jokko/core` `parseRate` when used in arithmetic.
 */
import { customType, timestamp, uuid } from 'drizzle-orm/pg-core';
import { uuidv7 } from '../common/ids.js';

/** Integer amount of an asset's smallest unit (wei, lamports, sats, sun). */
export const baseUnits = customType<{ data: bigint; driverData: string }>({
  dataType: () => 'numeric(78, 0)',
  toDriver: (value) => value.toString(),
  fromDriver: (value) => BigInt(value),
});

/** Integer amount of a fiat currency's minor unit (XOF francs, EUR/USD cents). */
export const fiatMinor = customType<{ data: bigint; driverData: string }>({
  dataType: () => 'numeric(38, 0)',
  toDriver: (value) => value.toString(),
  fromDriver: (value) => BigInt(value),
});

/** Exact decimal rate or price (e.g. "565.25"), kept as a string. */
export const rate = customType<{ data: string; driverData: string }>({
  dataType: () => 'numeric(38, 18)',
});

/**
 * Encrypted field (envelope-encrypted personal data, docs/02-security.md T14). The plaintext
 * never reaches the database; see `common/crypto/field-encryption.ts`.
 */
export const encrypted = customType<{ data: Buffer; driverData: Buffer }>({
  dataType: () => 'bytea',
});

/** Raw bytes (hashes). */
export const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType: () => 'bytea',
});

/** UUIDv7 primary key generated by the application. */
export const idColumn = () =>
  uuid('id')
    .primaryKey()
    .$defaultFn(() => uuidv7());

/** `created_at` / `updated_at` pair, UTC. `updated_at` is refreshed by the application. */
export const timestamps = () => ({
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdateFn(() => new Date()),
});

/** Single `created_at` for append-only tables (rows are never updated). */
export const createdAt = () => ({
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
