/**
 * Per-request identity attached by the guards and read by controllers through decorators.
 *
 * Kept on the Fastify request object (not in a global/async-local store) so it is impossible
 * for one request to see another request's user.
 */
import type { VerifiedPrivySession } from './privy-token.verifier.js';

/** The authenticated Jokko user making the request. */
export interface AuthenticatedUser {
  readonly id: string;
  readonly privyUserId: string;
  readonly status: 'active' | 'restricted' | 'closed';
  readonly locale: 'fr' | 'en';
  readonly country: string | null;
}

/** The app installation making the request (from `x-jokko-*` headers). */
export interface DeviceContext {
  /** Random ID generated by the app at install time. */
  readonly deviceId: string;
  readonly platform: 'ios' | 'android';
  readonly appVersion: string;
  /** Result of App Attest / Play Integrity verification for this request. */
  readonly attestation: 'verified' | 'unverified' | 'failed';
}

/** Everything the public-API guard attaches to the request. */
export interface JokkoRequestContext {
  readonly session: VerifiedPrivySession;
  /** `null` only on routes marked `@AllowUnregistered()` (first login / session bootstrap). */
  readonly user: AuthenticatedUser | null;
  readonly device: DeviceContext;
}

declare module 'fastify' {
  interface FastifyRequest {
    /** Set by `UserAuthGuard` on authenticated public-API routes. */
    jokko?: JokkoRequestContext;
  }
}
